name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check if Dockerfile is Dockerfile-processor + Dockerfile-client.in
      run: |
        DIFFS=$(diff <(cat Dockerfile-processor Dockerfile-client.in) Dockerfile | wc -l)
        if (( DIFFS > 0 ))
        then
          exit 1
        fi
