name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: echo test
    - name: Check if Dockerfile is Dockerfile-processor + Dockerfile-client.in
      run: |    
        cat Dockerfile-processor Dockerfile-client.in > test
        DIFFS="$(diff test Dockerfile )"
        if [[ ! -z "$DIFFS" ]]
        then
          echo "$DIFFS"
          exit 1
        fi
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Docker build
      run: docker build . -t ipeddocker/iped:latest
    - name: Docker tag
      run: docker tag ipeddocker/iped:latest ipeddocker/iped:${{ github.sha }}
    - name: Docker push
      run: |
        docker push ipeddocker/iped:latest
        docker push ipeddocker/iped:${{ github.sha }}
