name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: echo test
    - name: Check if Dockerfile is Dockerfile-processor + Dockerfile-client.in
      run: |    
        cat Dockerfile-processor Dockerfile-client.in > test
        DIFFS="$(diff test Dockerfile )"
        if [[ ! -z "$DIFFS" ]]
        then
          echo "$DIFFS"
          exit 1
        fi
