name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
      
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      
    - name: Docker build
      run: docker build . -f Dockerfile-centos8 -t ipeddocker/iped:${GITHUB_REF#refs/tags/}
      
    - name: Docker push - semver
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker push ipeddocker/iped:${GITHUB_REF#refs/tags/}
