name: CI/CD

on: [push]

jobs:
  check_Dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check if Dockerfile is Dockerfile-processor + Dockerfile-client.in
      run: |    
        cat Dockerfile-processor Dockerfile-client.in > test
        DIFFS="$(diff test Dockerfile )"
        if [[ ! -z "$DIFFS" ]]
        then
          echo "$DIFFS"
          exit 1
        fi
  build:
    needs: [check_Dockerfile]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Docker build processor
      run: docker build . -t ipeddocker/iped:processor_${GITHUB_REF#refs/tags/} -f Dockerfile-processor
    - name: Docker build latest
      run: docker build . -t ipeddocker/iped:latest
    - name: Docker push latest
      run: docker push ipeddocker/iped:latest
    - name: Docker push - processor
      run: |
        docker push ipeddocker/iped:processor_${GITHUB_REF#refs/tags/}
    - name: Docker push - semver
      run: |
        docker tag ipeddocker/iped:latest ipeddocker/iped:${GITHUB_REF#refs/tags/}
        docker push ipeddocker/iped:${GITHUB_REF#refs/tags/}
